services:
  container-structure-test:
    image: ubuntu:18.04
    command: |
      chmod +x container-structure-test-linux-amd64 && cp container-structure-test-linux-amd64 /usr/local/bin/container-structure-test && container-structure-test test --image awesome:build --config cst.yml
    working_dir: /root
    volumes:
      - ./:/root
  hadolint:
    image: hadolint/hadolint:latest
    command: hadolint Dockerfile
    working_dir: /root
    volumes: 
      - ./:/root
