name: m3task0

on:
  push:
    branches: main
  schedule:
    - cron: "30 10 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone github
      - uses: actions/checkout@v3
        with:
          repository: ''
          
      - run: cd module3_task0/
      - run: make help
