---
name: module3_task1

"on":
  push:
  schedule:
    - cron: "30 10 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone the repo
        uses: actions/checkout@v3
        with:
          repository: ''

      - name: Running the setup
        run: ./module3_task1/setup.sh

      - name: Building
        run: cd module3_task1/ && make build

      - name: Run api
        run: cd module3_task1/ && make run
    
      - name: Create a test post
        run: cd module3_task1/ && POST_TITLE=welcometest POST_NAME=testing make post

      - name: Testing
        run: cd module3_task1/ && make test

      - name: Cleaning
        run: cd module3_task1/ && make clean
