name: m3task0

"on":
  push:
    branches: main
  schedule:
    - cron: "30 10 * * *"

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - name: Clone repo
      - uses: PhYdrogen/holbertonschool-validation@master
      - run: cd module3_task0/
      - run: make help
