name: module 3 task 0

on:
  push:
  schedule:
    - cron: "30 10 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ''
          
      - run: cd module3_task0/ && make help
